In [1]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [2]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 

In [10]:
import pandas as pd
import numpy as np 
data= pd.read_csv('Train.csv')

In [11]:
data

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047   
1              DRC01        5.920          Regular         0.019278   
2              FDN15       17.500          Low Fat         0.016760   
3              FDX07       19.200          Regular         0.000000   
4              NCD19        8.930          Low Fat         0.000000   
...              ...          ...              ...              ...   
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049   
1               Soft Drinks   48.2692            OUT018   
2                      Meat  141.6180            OUT049   
3     Fruits and Vegetables  182.0950            OUT010   
4                 Household   53.8614            OUT013   
...                     ...       ...               ...   
8518            Snack Foods  214.5218            OUT013   
8519           Baking Goods  108.1570            OUT045   
8520     Health and Hygiene   85.1224            OUT035   
8521            Snack Foods  103.1332            OUT018   
8522            Soft Drinks   75.4670            OUT046   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1   
1                          2009      Medium               Tier 3   
2                          1999      Medium               Tier 1   
3                          1998         NaN               Tier 3   
4                          1987        High               Tier 3   
...                         ...         ...                  ...   
8518                       1987        High               Tier 3   
8519                       2002         NaN               Tier 2   
8520                       2004       Small               Tier 2   
8521                       2009      Medium               Tier 3   
8522                       1997       Small               Tier 1   

            Outlet_Type  Item_Outlet_Sales  
0     Supermarket Type1          3735.1380  
1     Supermarket Type2           443.4228  
2     Supermarket Type1          2097.2700  
3         Grocery Store           732.3800  
4     Supermarket Type1           994.7052  
...                 ...                ...  
8518  Supermarket Type1          2778.3834  
8519  Supermarket Type1           549.2850  
8520  Supermarket Type1          1193.1136  
8521  Supermarket Type2          1845.5976  
8522  Supermarket Type1           765.6700  

[8523 rows x 12 columns]

In [12]:
from sklearn.model_selection import train_test_split

x = data.drop("Item_Outlet_Sales", axis = 1) 

y = data["Item_Outlet_Sales"].values.reshape(-1,1)
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size =0.20, random_state = 3)

In [13]:
 from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

data['Outlet_Identifier']= label_encoder.fit_transform(data['Outlet_Identifier'])
data['Outlet_Identifier'].unique()

array([9, 3, 0, 1, 5, 7, 2, 8, 6, 4])

In [14]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

data['Item_Identifier']= label_encoder.fit_transform(data['Item_Identifier'])
data['Item_Identifier'].unique()

array([ 156,    8,  662, ..., 1323, 1524, 1519])

In [15]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

data['Item_Fat_Content']= label_encoder.fit_transform(data['Item_Fat_Content'])
data['Item_Fat_Content'].unique()

array([1, 2, 3, 0, 4])

In [16]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

data['Item_Type']= label_encoder.fit_transform(data['Item_Type'])
data['Item_Type'].unique()

array([ 4, 14, 10,  6,  9,  0, 13,  5,  2,  8,  7,  3,  1, 15, 11, 12])

In [17]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

data['Outlet_Size']= label_encoder.fit_transform(data['Outlet_Size'])
data['Outlet_Size'].unique()

array([1, 3, 0, 2])

In [18]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

data['Outlet_Location_Type']= label_encoder.fit_transform(data['Outlet_Location_Type'])
data['Outlet_Location_Type'].unique() 

array([0, 2, 1])

In [19]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

data['Outlet_Type']= label_encoder.fit_transform(data['Outlet_Type'])
data['Outlet_Type'].unique()

array([1, 2, 0, 3])

In [20]:
data

Item_Identifier  Item_Weight  Item_Fat_Content  Item_Visibility  \
0                 156        9.300                 1         0.016047   
1                   8        5.920                 2         0.019278   
2                 662       17.500                 1         0.016760   
3                1121       19.200                 2         0.000000   
4                1297        8.930                 1         0.000000   
...               ...          ...               ...              ...   
8518              370        6.865                 1         0.056783   
8519              897        8.380                 2         0.046982   
8520             1357       10.600                 1         0.035186   
8521              681        7.210                 2         0.145221   
8522               50       14.800                 1         0.044878   

      Item_Type  Item_MRP  Outlet_Identifier  Outlet_Establishment_Year  \
0             4  249.8092                  9                       1999   
1            14   48.2692                  3                       2009   
2            10  141.6180                  9                       1999   
3             6  182.0950                  0                       1998   
4             9   53.8614                  1                       1987   
...         ...       ...                ...                        ...   
8518         13  214.5218                  1                       1987   
8519          0  108.1570                  7                       2002   
8520          8   85.1224                  6                       2004   
8521         13  103.1332                  3                       2009   
8522         14   75.4670                  8                       1997   

      Outlet_Size  Outlet_Location_Type  Outlet_Type  Item_Outlet_Sales  
0               1                     0            1          3735.1380  
1               1                     2            2           443.4228  
2               1                     0            1          2097.2700  
3               3                     2            0           732.3800  
4               0                     2            1           994.7052  
...           ...                   ...          ...                ...  
8518            0                     2            1          2778.3834  
8519            3                     1            1           549.2850  
8520            2                     1            1          1193.1136  
8521            1                     2            2          1845.5976  
8522            2                     0            1           765.6700  

[8523 rows x 12 columns]

In [21]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [22]:
data

Item_Identifier  Item_Weight  Item_Fat_Content  Item_Visibility  \
0                 156        9.300                 1         0.016047   
1                   8        5.920                 2         0.019278   
2                 662       17.500                 1         0.016760   
3                1121       19.200                 2         0.000000   
4                1297        8.930                 1         0.000000   
...               ...          ...               ...              ...   
8518              370        6.865                 1         0.056783   
8519              897        8.380                 2         0.046982   
8520             1357       10.600                 1         0.035186   
8521              681        7.210                 2         0.145221   
8522               50       14.800                 1         0.044878   

      Item_Type  Item_MRP  Outlet_Identifier  Outlet_Establishment_Year  \
0             4  249.8092                  9                       1999   
1            14   48.2692                  3                       2009   
2            10  141.6180                  9                       1999   
3             6  182.0950                  0                       1998   
4             9   53.8614                  1                       1987   
...         ...       ...                ...                        ...   
8518         13  214.5218                  1                       1987   
8519          0  108.1570                  7                       2002   
8520          8   85.1224                  6                       2004   
8521         13  103.1332                  3                       2009   
8522         14   75.4670                  8                       1997   

      Outlet_Size  Outlet_Location_Type  Outlet_Type  Item_Outlet_Sales  
0               1                     0            1          3735.1380  
1               1                     2            2           443.4228  
2               1                     0            1          2097.2700  
3               3                     2            0           732.3800  
4               0                     2            1           994.7052  
...           ...                   ...          ...                ...  
8518            0                     2            1          2778.3834  
8519            3                     1            1           549.2850  
8520            2                     1            1          1193.1136  
8521            1                     2            2          1845.5976  
8522            2                     0            1           765.6700  

[8523 rows x 12 columns]

In [23]:
pip install --upgrade xgboost

Note: you may need to restart the kernel to use updated packages.


In [24]:
import pandas as pd

data = pd.read_csv("Test.csv")

In [25]:
 data.info()

    

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5681 entries, 0 to 5680
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            5681 non-null   object 
 1   Item_Weight                4705 non-null   float64
 2   Item_Fat_Content           5681 non-null   object 
 3   Item_Visibility            5681 non-null   float64
 4   Item_Type                  5681 non-null   object 
 5   Item_MRP                   5681 non-null   float64
 6   Outlet_Identifier          5681 non-null   object 
 7   Outlet_Establishment_Year  5681 non-null   int64  
 8   Outlet_Size                4075 non-null   object 
 9   Outlet_Location_Type       5681 non-null   object 
 10  Outlet_Type                5681 non-null   object 
dtypes: float64(3), int64(1), object(7)
memory usage: 488.3+ KB


In [26]:
 cols_to_drop = ["Item_Identifier", "Item_Weight", "Item_Fat_Content", "Item_Visibility"]

data.drop(cols_to_drop, axis=1, inplace=True)

In [27]:
missing_props = data.isna().mean(axis=0)

In [28]:
over_threshold = missing_props[missing_props >= 0.4]
over_threshold

Series([], dtype: float64)

In [29]:
data.drop(over_threshold.index, 
          axis=1, 
          inplace=True)

In [30]:
X = data.drop("Outlet_Type", axis=1)
y = data.Outlet_Type

In [31]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

categorical_pipeline = Pipeline(
    steps=[
        ("impute", SimpleImputer(strategy="most_frequent")),
        ("oh-encode", OneHotEncoder(handle_unknown="ignore", sparse=False)),
    ]
)

In [32]:
from sklearn.preprocessing import StandardScaler

numeric_pipeline = Pipeline(
    steps=[("impute", SimpleImputer(strategy="mean")), 
           ("scale", StandardScaler())]
)

In [33]:
cat_cols = X.select_dtypes(exclude="number").columns
num_cols = X.select_dtypes(include="number").columns

In [34]:
from sklearn.compose import ColumnTransformer

full_processor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_pipeline, num_cols),
        ("categorical", categorical_pipeline, cat_cols),
    ]
)